/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.25
 * Generated at: 2024-07-02 07:26:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.assesmentPortal.DatabaseConnection;

public final class subjectQuestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.assesmentPortal.DatabaseConnection");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
	response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate");
	response.setHeader("Pragma", "no-cache");
	response.setDateHeader("Expires", 0);
	
	if (session.getAttribute("user") == null) {
        response.sendRedirect("index.jsp");
        return;
    } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    String id = request.getParameter("id");
    String tag = "";
    int numOfQuestions = 0;
    try{
    	Connection conn = DatabaseConnection.getConnection();
    	String query = "Select * from testsubjects where id= ?";
    	PreparedStatement ps = conn.prepareStatement(query);
    	ps.setInt(1, Integer.parseInt(id));
    	ResultSet resultSet = ps.executeQuery();
    	
    	if (resultSet.next()){
    		tag = resultSet.getString("subjectName");
    		numOfQuestions = resultSet.getInt("noOfQuestion");
    	}
    	
    	System.out.println(tag + " " + numOfQuestions);
    	
    	
    }catch(SQLException e){
    	e.printStackTrace();    	
    }

    if ("POST".equalsIgnoreCase(request.getMethod())) {
        for (int i = 0; i < numOfQuestions; i++) {
            String question = request.getParameter("question" + i);
            String optionA = request.getParameter("optionA" + i);
            String optionB = request.getParameter("optionB" + i);
            String optionC = request.getParameter("optionC" + i);
            String optionD = request.getParameter("optionD" + i);
            String correctOption = request.getParameter("correctOption" + i);

            try {
                Connection connection = DatabaseConnection.getConnection();
                String insertQuery = "INSERT INTO question (testSubjectName, testQuestion, optionA, optionB, optionC, optionD, correctOption) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement preparedStatement = connection.prepareStatement(insertQuery);
                preparedStatement.setString(1, tag);
                preparedStatement.setString(2, question);
                preparedStatement.setString(3, optionA);
                preparedStatement.setString(4, optionB);
                preparedStatement.setString(5, optionC);
                preparedStatement.setString(6, optionD);
                preparedStatement.setString(7, correctOption);
                preparedStatement.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        try{
        	String passMarks = request.getParameter("passMarks");
        	
        	Connection conn = DatabaseConnection.getConnection();
        	String query = "UPDATE testsubjects SET passMarks = ? where id= ?";
        	PreparedStatement ps = conn.prepareStatement(query);
        	ps.setInt(1, Integer.parseInt(passMarks));
        	ps.setInt(2, Integer.parseInt(id));
        	ps.executeUpdate();
			
        	
        	
        }catch(SQLException e){
        	e.printStackTrace();    	
        }
        response.sendRedirect("admindashboard.jsp");
    }
    

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Questions Adding</title>\r\n");
      out.write("<style>\r\n");
      out.write("	form {\r\n");
      out.write("	    max-width: 600px;\r\n");
      out.write("	    margin: auto;\r\n");
      out.write("	    padding: 1em;\r\n");
      out.write("	    background: #f9f9f9;\r\n");
      out.write("	    border-radius: 5px;\r\n");
      out.write("	}\r\n");
      out.write("	div {\r\n");
      out.write("	    margin-bottom: 1em;\r\n");
      out.write("	}\r\n");
      out.write("	label {\r\n");
      out.write("	    margin-bottom: .5em;\r\n");
      out.write("	    color: #333333;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("	input {\r\n");
      out.write("	    border: 1px solid #CCCCCC;\r\n");
      out.write("	    padding: .5em;\r\n");
      out.write("	    width: calc(100% - 1em);\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	button {\r\n");
      out.write("	    padding: 10px 20px;\r\n");
      out.write("	    background-color: #4CAF50;\r\n");
      out.write("	    color: white;\r\n");
      out.write("	    border: none;\r\n");
      out.write("	    cursor: pointer;\r\n");
      out.write("	    border-radius: 5px;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	}\r\n");
      out.write("	button:hover {\r\n");
      out.write("	    background-color: #45a049;\r\n");
      out.write("	}\r\n");
      out.write("	header, footer {\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("    color: white;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 10px 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("    <h1>Add Question</h1>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form method=\"post\">\r\n");
      out.write("    ");

        for (int i = 0; i < numOfQuestions; i++) {
    
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"question");
      out.print(i);
      out.write("\">Question ");
      out.print(i+1);
      out.write("</label>\r\n");
      out.write("        <input type=\"text\" id=\"question");
      out.print(i);
      out.write("\" name=\"question");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"optionA");
      out.print(i);
      out.write("\">Option A</label>\r\n");
      out.write("        <input type=\"text\" id=\"optionA");
      out.print(i);
      out.write("\" name=\"optionA");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"optionB");
      out.print(i);
      out.write("\">Option B</label>\r\n");
      out.write("        <input type=\"text\" id=\"optionB");
      out.print(i);
      out.write("\" name=\"optionB");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"optionC");
      out.print(i);
      out.write("\">Option C</label>\r\n");
      out.write("        <input type=\"text\" id=\"optionC");
      out.print(i);
      out.write("\" name=\"optionC");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"optionD");
      out.print(i);
      out.write("\">Option D</label>\r\n");
      out.write("        <input type=\"text\" id=\"optionD");
      out.print(i);
      out.write("\" name=\"optionD");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"correctOption");
      out.print(i);
      out.write("\">Correct Option</label>\r\n");
      out.write("        <input type=\"text\" id=\"correctOption");
      out.print(i);
      out.write("\" name=\"correctOption");
      out.print(i);
      out.write("\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <input type=\"hidden\" id=\"tag\" name=\"tag\" value=\"");
      out.print( tag );
      out.write("\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("        <label for=\"passMarks\">Passing Marks</label>\r\n");
      out.write("        <input type=\"text\" id=\"passMarks\" name=\"passMarks\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div>\r\n");
      out.write("        <button type=\"submit\">Submit Questions</button>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("<footer>\r\n");
      out.write("    <p>&copy; 2023 Your Company</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
